### ISSUE TITLE
Rpi4 build ld.lld: error: relocation R_AARCH64_ADR_PREL_PG_HI21 out of range

### ISSUE THREAD

**Issue by iceye** [lineage-rpi/android_kernel_manifest#2]
Hello,
I'm trying to build lineage 20.0 kernel, I followed the steps from the readme.
OS: Ubuntu 20.04 with a working build env
gcc --version
gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0

same version for g++ and cpp

Compilation seems ok until:

>BUILD_CONFIG=common/build.config.rpi4 ./build/build.sh
...
...
  AR      drivers/android/built-in.a
  CC      drivers/staging/vc04_services/bcm2835-isp/bcm2835-v4l2-isp.o
  AR      drivers/iio/built-in.a
  CC      drivers/gnss/ubx.o
  CC      drivers/staging/vc04_services/interface/vchiq_arm/vchiq_core.o
  AR      drivers/gnss/built-in.a
  CC      drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.o
  AR      drivers/staging/vc04_services/bcm2835-codec/built-in.a
  CC      drivers/staging/vc04_services/interface/vchiq_arm/vchiq_debugfs.o
  AR      drivers/staging/vc04_services/bcm2835-isp/built-in.a
  CC      drivers/staging/vc04_services/interface/vchiq_arm/vchiq_connected.o
  CC      drivers/staging/vc04_services/interface/vchiq_arm/vchiq_dev.o
  AR      drivers/staging/vc04_services/built-in.a
  AR      drivers/staging/built-in.a
  AR      drivers/built-in.a
  GEN     .version
  CHK     include/generated/compile.h
  LD      vmlinux.o
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  LD      .tmp_vmlinux.kallsyms1

**ld.lld: error: relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: 274729865216 is not in [-4294967296, 4294967295]
ld.lld: error: relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: 274729865216 is not in [-4294967296, 4294967295]
ld.lld: error: relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: 274729865216 is not in [-4294967296, 4294967295]
ld.lld: error: relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: 274729865216 is not in [-4294967296, 4294967295]
ld.lld: error: relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: 274729865216 is not in [-4294967296, 4294967295]**

On the same machine, same env running lineage 19.1 build runs without errors.

> BUILD_CONFIG=common/build.config.rpi4 ./build/build.sh
...
...
  AR      drivers/media/platform/bcm2835/built-in.a
  AR      drivers/media/platform/built-in.a
  AR      drivers/media/common/videobuf2/built-in.a
  AR      drivers/media/common/built-in.a
  AR      drivers/media/built-in.a
  AR      drivers/built-in.a
  GEN     .version
  CHK     include/generated/compile.h
  LD      vmlinux.o
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  LD      .tmp_vmlinux.kallsyms1
  KSYMS   .tmp_vmlinux.kallsyms1.S
  AS      .tmp_vmlinux.kallsyms1.S
  LD      .tmp_vmlinux.kallsyms2
  KSYMS   .tmp_vmlinux.kallsyms2.S
  AS      .tmp_vmlinux.kallsyms2.S
  LD      vmlinux
  SORTTAB vmlinux
  SYSMAP  System.map
  OBJCOPY arch/arm64/boot/Image
 set +x
========================================================
 Copying files
  arch/arm64/boot/Image
  arch/arm64/boot/dts/broadcom/bcm2711-rpi-4-b.dtb
  arch/arm64/boot/dts/broadcom/bcm2711-rpi-400.dtb
  arch/arm64/boot/dts/broadcom/bcm2711-rpi-cm4.dtb
  arch/arm64/boot/dts/broadcom/bcm2711-rpi-cm4s.dtb
========================================================
 Installing UAPI kernel headers:
make: Entering directory '/home/osboxes/rpi4_lineageos19/out/common'
  HOSTCC  scripts/unifdef
  ...
  ...
  
Build envs for 19.1 and 20.0 are isolated (2 different folders).

In both cases kernel config has been customized (monolithic kernel, only needed drivers). The configuration has been manually ported (checkbox by checkbox :( ) from 19.1 to 20.0 using config.sh interface. 
Lineage 19.1 built kernel is working both on lineage 19.1 and AOSP 12L.

Looking around for solution seems not helping, I found something about additional CFLAGS -fPIC. It seems the flags has no effect but I'm not sure how to force flags to the build process.

Kernel .out Config lineage 20.0: https://docs.google.com/document/d/1djrR1y2fTyt4_Wu528xpdisRPS3H4-DbTabG4yNrDDk/edit?usp=share_link
Common Defconfig: https://docs.google.com/document/d/1L7UcFbtB6yz64tqPr9CE69Tc02oYqaLdWs1aPBksESk/edit?usp=share_link

Help would be appreciated

**Comment by iceye** [comment]
Fresh build from repo is generating the kernel image but it's not booting (boot loop after 3-4 seconds)...looking around for the flag causing the issue and how to build a working kernel for Lineage 20.0

**Comment by KonstaT** [comment]
Please follow the instructions https://github.com/lineage-rpi/android_kernel_manifest/tree/lineage-20.0 on how to setup the build environment for Android 13 kernel. It's different on Android 12 and 13 so you can't just switch the kernel branch.

That defconfig is nowhere close what you'd get when building the kernel as instructed. E.g. BPF_JIT_ALWAYS_ON enabled is a requirement for Android to boot.

If you want to modify the defconfig, edit arch/arm64/configs/lineageos_rpi4_defconfig on the kernel source. To regenerate the defconfig, you can run `BUILD_CONFIG=common/build.config.rpi4.defconfig SKIP_MRPROPER=1 build/build.sh` from the root of the environment.

Closing as this is most likely due to your own modifications.
